name: pda_scanner
description: "一个能支持多种PDA扫码的Flutter插件"
version: 1.0.2
homepage: https://gitee.com/zengxingshun/flutter_plugin_pda_scanner

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  # shared_preferences
  shared_preferences: ^2.2.2
  visibility_detector: ^0.4.0+2
  # 播放音频
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.jerome.pda_scanner
        pluginClass: PdaScannerPlugin