name: flutter_plugin_pda_scanner
description: 'A PDA barcode scanning plugin, supporting multiple brands and models of PDA devices, including but not limited to Zebra, Hikvision, Invengo, Speedata, and Seuic.'
version: 3.0.5+2
homepage: https://gitee.com/zengxingshun/flutter_plugin_pda_scanner/blob/master/README_en.md
repository: https://github.com/JeromeTseng/flutter_plugin_pda_scanner

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  audioplayers: 6.1.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.jerometseng.pdascanner
        pluginClass: PdaScannerPlugin
  assets:
    - assets/audio/